//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etaxproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_HousesMaster
    {
        public int UniQueHousNo { get; set; }
        public string OwnerName { get; set; }
        public string TelephonNo { get; set; }
        public string Email { get; set; }
        public string ActualHouseNo { get; set; }
        public Nullable<System.DateTime> HouseRegistrationdate { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public Nullable<int> PlotId { get; set; }
        public Nullable<int> BuildingApprovalNo { get; set; }
        public Nullable<int> C_M_P_Id { get; set; }
    }
}
