//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etaxproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class watertax
    {
        public int UniQueHousNo { get; set; }
        public Nullable<int> watertaxid { get; set; }
        public string paymentamount { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
    }
}
